#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $this_dir)
dir_name=rcook.github.io

if [ "$(basename $repo_dir)" != "$dir_name" ]; then
  echo "Parent directory must be $dir_name"
  exit 1
fi

# Extract Gist IDs from post text
ids=$(
  cd $repo_dir &&
  git grep '{% '$(echo 'g')'ist ' |
    sed -e 's/^.*{% '$(echo 'g')'ist \([0-9a-fA-F][0-9a-fA-F]*\) .*$/\1/' |
    sort |
    uniq
)

for id in $ids; do
  date=$(
    git grep $id 2>&1 |
      head -n 1 |
      sed -e 's/^_posts\/\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\)-.*$/\1/'
  )

  git_url=git@gist.github.com:$id.git
  gist_dir=$repo_dir/_gists/gist-$date-$id

  if [ -d "$gist_dir" ]; then
    if [ -d "$gist_dir/.git" ]; then
      output0=$(cd "$gist_dir" && git status --porcelain)
      output1=$(cd "$gist_dir" && git status --porcelain --branch)
      if [[ "${#output0}" -gt 0 || "$output1" == *"["* ]]; then
        echo -e "\n\e[44m$gist_dir\e[49m\n"
        (cd "$gist_dir" && git status)
      fi
    else
      echo "Invalid Gist directory $gist_dir"
    fi
  else
    git clone $git_url $gist_dir
  fi
done
